######################################################################## Dockerfile to build model 1
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model1
RUN cp -n /model1/model_a.py /model1/model.py
RUN conda install -y pip
RUN conda install -y --file /model1/requirements.txt
