######################################################################## Dockerfile to build model 2
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model2
RUN cp -n /model2/model_b.py /model2/model.py
RUN conda install -y pip
RUN conda install -y --file /model2/requirements.txt
