######################################################################## Dockerfile to build model 5
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model5
RUN cp -n /model5/model_c.py /model5/model.py
RUN conda install -y pip
RUN conda install -y --file /model5/requirements.txt
