######################################################################## Dockerfile to build model 6
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model6
RUN cp -n /model6/model_d.py /model6/model.py
RUN conda install -y pip
RUN conda install -y --file /model6/requirements.txt
