######################################################################## Dockerfile to build model 4
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model4
RUN cp -n /model4/model_b.py /model4/model.py
RUN conda install -y pip
RUN conda install -y --file /model4/requirements.txt
