#######################################################################
# Dockerfile to build model 1
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model_a.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model_a.py /model_a.py
COPY ./example_a.py /example_a.py
