######################################################################## Dockerfile to build model 31
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model31
RUN cp -n /model31/modeld.py /model31/model.py
RUN conda install -y pip
RUN conda install -y --file /model31/requirements.txt
