#######################################################################
# Dockerfile to build model 29
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./modelb.py model.py
COPY ./requirements.txt requirements.txt
COPY ./modelb.py /modelb.py
COPY ./exampleb.py /exampleb.py
