######################################################################## Dockerfile to build model 29
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model29
RUN cp -n /model29/modelb.py /model29/model.py
RUN conda install -y pip
RUN conda install -y --file /model29/requirements.txt
