#######################################################################
# Dockerfile to build model 31
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./modeld.py model.py
COPY ./requirements.txt requirements.txt
COPY ./modeld.py /modeld.py
COPY ./exampled.py /exampled.py
