######################################################################## Dockerfile to build model 25
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model25
RUN cp -n /model25/modeld.py /model25/model.py
RUN conda install -y pip
RUN conda install -y --file /model25/requirements.txt
