#######################################################################
# Dockerfile to build model 28
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./modela.py model.py
COPY ./requirements.txt requirements.txt
COPY ./modela.py /modela.py
COPY ./examplea.py /examplea.py
