######################################################################## Dockerfile to build model 24
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model24
RUN cp -n /model24/modelc.py /model24/model.py
RUN conda install -y pip
RUN conda install -y --file /model24/requirements.txt
