######################################################################## Dockerfile to build model 30
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model30
RUN cp -n /model30/modelc.py /model30/model.py
RUN conda install -y pip
RUN conda install -y --file /model30/requirements.txt
