#######################################################################
# Dockerfile to build model 30
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./modelc.py model.py
COPY ./requirements.txt requirements.txt
COPY ./modelc.py /modelc.py
COPY ./examplec.py /examplec.py
