######################################################################## Dockerfile to build model 34
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model34
RUN cp -n /model34/model_c.py /model34/model.py
RUN conda install -y pip
RUN conda install -y --file /model34/requirements.txt
