######################################################################## Dockerfile to build model 26
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model26
RUN cp -n /model26/model_a.py /model26/model.py
RUN conda install -y pip
RUN conda install -y --file /model26/requirements.txt
