######################################################################## Dockerfile to build model 37
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model37
RUN cp -n /model37/model_f.py /model37/model.py
RUN conda install -y pip
RUN conda install -y --file /model37/requirements.txt
