#######################################################################
# Dockerfile to build model 20
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model_d.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model_d.py /model_d.py
COPY ./example_d.py /example_d.py
