######################################################################## Dockerfile to build model 23
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model23
RUN cp -n /model23/model_c.py /model23/model.py
RUN conda install -y pip
RUN conda install -y --file /model23/requirements.txt
