#######################################################################
# Dockerfile to build model 16
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model.py /model.py
COPY ./example.py /example.py
