#######################################################################
# Dockerfile to build model 12
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model_e.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model_e.py /model_e.py
COPY ./example_e.py /example_e.py
