######################################################################## Dockerfile to build model 13
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model13
RUN cp -n /model13/model_c.py /model13/model.py
RUN conda install -y pip
RUN conda install -y --file /model13/requirements.txt
