#######################################################################
# Dockerfile to build model 9
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model_b.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model_b.py /model_b.py
COPY ./example_b.py /example_b.py
