######################################################################## Dockerfile to build model 8
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model8
RUN cp -n /model8/model_b.py /model8/model.py
RUN conda install -y pip
RUN conda install -y --file /model8/requirements.txt
