######################################################################## Dockerfile to build model 11
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model11
RUN cp -n /model11/model_a.py /model11/model.py
RUN conda install -y pip
RUN conda install -y --file /model11/requirements.txt
