######################################################################## Dockerfile to build model 10
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model10
RUN cp -n /model10/model_d.py /model10/model.py
RUN conda install -y pip
RUN conda install -y --file /model10/requirements.txt
