#######################################################################
# Dockerfile to build model 10
# Based on elyase/conda, produced by dockerwriter.py
#######################################################################

FROM elyase/conda
MAINTAINER "DOI RISKS"
COPY ./ model
COPY ./model_c.py model.py
COPY ./requirements.txt requirements.txt
COPY ./model_c.py /model_c.py
COPY ./example_c.py /example_c.py
