######################################################################## Dockerfile to build model 9
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model9
RUN cp -n /model9/model_c.py /model9/model.py
RUN conda install -y pip
RUN conda install -y --file /model9/requirements.txt
