######################################################################## Dockerfile to build model 12
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model12
RUN cp -n /model12/model_b.py /model12/model.py
RUN conda install -y pip
RUN conda install -y --file /model12/requirements.txt
