######################################################################## Dockerfile to build model 19
# Based on continuumio/miniconda, produced by dockerwriter.py
#######################################################################

FROM continuumio/miniconda
MAINTAINER "DOI RISKS"
ADD ./ model19
RUN cp -n /model19/model_a.py /model19/model.py
RUN conda install -y pip
RUN conda install -y --file /model19/requirements.txt
